[project]
name = "transaction_parser"
authors = [{ name = "Resilient Tech", email = "info@resilient.tech" }]
description = "AI-powered add-on for ERPNext that extracts data from PDFs and creates draft records automatically."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "pre_commit~=4.1.0",
    "ocrmypdf~=16.10.0",
    "rapidfuzz~=3.12.2",
    "pymupdf~=1.26.3",
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "B", "RUF"]

ignore = [
    "E501", # line too long
    "F401", # module imported but unused
    "F403", # can't detect undefined names from * import
    "F405", # can't detect undefined names from * import
]

typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
erpnext = ">=15.0.0,<16.0.0"
